backtest:
  data:
    trading_symbols: [ "COLPAL", "HDFCBANK", "IDEA", "RELIANCE", "INFY", "TCS" ]
    intervals: [ "1m", "3m", "5m", "10m" ]
    from_date: "2023-01-01 09:15:00"
    to_date: "2025-07-31 15:30:00"
  strategies:
    - name: "EMA_CROSS"
      fast_list: [ 8, 9, 12 ]
      slow_list: [ 20, 21, 26 ]
    - name: "SMA_CROSS"
      fast_list: [ 20, 50 ]
      slow_list: [ 50, 200 ]
    - name: "RSI"
      period_list: [ 14, 21 ]
      overbought_list: [ 70, 80 ]
      oversold_list: [ 30, 20 ]
      mode_list: [ "simple", "exponential" ]
    - name: "MACD"
      fast_list: [ 12 ]
      slow_list: [ 26 ]
      signal_list: [ 9 ]
    - name: "SUPER_TREND"
      period_list: [ 10, 14 ]
      multiplier_list: [ 2.0, 3.0 ]
    - name: "ADX"
      period_list: [ 14 ]
      threshold_list: [ 20, 25 ]
      exit_threshold_list: [ 15 ]
    - name: "BOLLINGER"
      period_list: [ 20 ]
      stddev_list: [ 2.0 ]
    - name: "CCI"
      period_list: [ 20 ]
      entry_list: [ -100 ]
      exit_list: [ 100 ]
    - name: "DONCHIAN"
      period_list: [ 20 ]
    - name: "VOLUME_SPIKE"
      period_list: [ 20 ]
      spike_mult_list: [ 2.0 ]
    - name: "WILLIAMS_R"
      period_list: [ 14 ]
      overbought_list: [ -20 ]
      oversold_list: [ -80 ]
    - name: "STOCHASTIC"
      k_period_list: [ 14 ]
      d_period_list: [ 3 ]
      overbought_list: [ 80 ]
      oversold_list: [ 20 ]
    - name: "ATR"
      period_list: [ 14 ]
      spike_mult_list: [ 2.0 ]
    - name: "MFI"
      period_list: [ 14 ]
    - name: "AROON"
      period_list: [ 14 ]
    - name: "CHAIKIN_MF"
      period_list: [ 20 ]
    - name: "DEMA"
      period_list: [ 21 ]
    - name: "ENVELOPE"
      period_list: [ 20 ]
      percent_list: [ 0.025 ]
    - name: "HULL_MA"
      period_list: [ 21 ]
    - name: "KELTNER"
      period_list: [ 20 ]
      multiplier_list: [ 2.0 ]
    - name: "MOMENTUM"
      period_list: [ 10 ]
    - name: "OBV"
      ma_period_list: [ 20 ]
    - name: "PIVOT"
      ma_period_list: [ 1 ]
    - name: "PSAR"
      af_list: [ 0.02 ]
      max_af_list: [ 0.2 ]
    - name: "ROC"
      period_list: [ 10 ]
      threshold_list: [ 1.0 ]
    - name: "STOCH_RSI"
      period_list: [ 14 ]
    - name: "TEMA"
      period_list: [ 21 ]
    - name: "TRIX"
      period_list: [ 15 ]
    - name: "ULTIMATE_OSC"
      period_short_list: [ 7 ]
      period_medium_list: [ 14 ]
      period_long_list: [ 28 ]
    - name: "VWAP"
      period_list: [ 0, 10, 50 ]
  simulation_params:
    train_split: 0.7
    initial_capital: 500000
    stop_loss_pct: 0.02           # 2%
    trailing_stop_loss_pct: 0.02  # 2%
    target_profit_pct: 0.04       # 4%
    hold_min_bars: 2
    hold_max_bars: 120
    contract_size: 1
    fill_rate: 1.0
    slippage_pct: 0.001
    intraday_only: true
  debug_logs: true
