kite:
  api_key: "YOUR_KEY"
  api_secret: "YOUR_SECRET"

historical:
  trading_symbols: [ "COLPAL", "HDFCBANK", "IDEA", "RELIANCE", "INFY", "TCS" ]
  intervals: [ "1m", "3m", "5m", "10m" ]
  from_date: "2023-01-01 09:15:00"
  to_date: "2025-07-31 15:30:00"

websocket:
  default_symbols: [ "COLPAL", "HDFCBANK", "IDEA", "RELIANCE", "INFY", "TCS" ]
  reconnect: true
  reconnect_max_tries: 5
  market_open_hour: 9
  market_open_minute: 00
  market_close_hour: 15
  market_close_minute: 30

brokerage:
  segment: "EQUITY_INTRADAY"
  exchange: "NSE"
