kite:
  api_key: "YOUR_KEY"
  api_secret: "YOUR_SECRET"

historical:
  trading_symbol: "HDFCBANK"
  from_date: "2025-01-01 09:15:00"
  to_date: "2025-07-19 15:30:00"
  interval: "1m"

websocket:
  default_symbols: [ "COLPAL", "HDFCBANK", "IDEA", "RELIANCE", "INFY", "TCS" ]
  reconnect: true
  reconnect_max_tries: 5
  market_open_hour: 9
  market_open_minute: 00
  market_close_hour: 15
  market_close_minute: 30

indicators:
  - SMA_CROSS
  - EMA_CROSS
  - RSI
  - ADX
  - BOLLINGER
  - CCI
  - DONCHIAN
  - MACD
  - SUPER_TREND
  - VOLUME_SPIKE
